spring:
  application:
    name: ForoHubChallenge

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOST_FORO_DB}/${NAME_DB_FORO}
    username: ${USER_NAME_DB}
    password: ${PASSWORD_FORO_DB}

server:
  error:
    include-stacktrace: never
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
  dialect: org.hibernate.dialect.MySQLDialect

api:
  security:
    secret: ${JWT_SECRET:12345}